-- Core authz seed (permissions, system roles, tenant, role grants) moved to:
--   supabase/seed/authz.json
--   supabase/functions/ensure-authz-seed
--   pnpm seed:app  (or db:reset:seed)
--
-- Intentionally a no-op; run the seed pipeline after migrations.
